config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Good job setting up a root route and using nested resources appropriately
  root to: "posts#index"
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  # To properly associate posts with their users, you should uncomment the line above,
  # add a User in your seed data, and update all of the posts in the seed data with
  # that user as their user:. Also do the same for comments.
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # Nice use of before_action to authenticate login
end

app/controllers/comment_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user: current_user))
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      redirect_to :back
    end
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      redirect_to :back
    end
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      redirect_to :back
    end
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create!(post_params.merge(user: current_user))
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to :back
    end
    # We also should test that the user is allowed to modify posts in our controller
    # actions, like above
  end

  def update
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to :back
    end
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to :back
    end
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<%# You can delete any unused view templates, like this one %>

app/views/comments/new.html.erb
<h3>New Comment</h3>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GOOD MEAL</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= video_tag "awesome Sony ultra hd food 4K Demo video 2016", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>
  <main>
    <%# Maybe think about formatting these alerts and links into a navbar affixed
    to the top of the page %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- <%= image_tag('scribble.png') %>
    <%= link_to "Sign Up", new_user_registration_path %> -->
    <%# Be careful commenting out code in ERB like above, it can cause errors. The proper
    format is like this. %>
    <% if !current_user %>
        <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Sign In", new_user_session_path %>
    <% end %>
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>


    <%= yield %>
  </main>
</body>
</html>

app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_area :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<%= link_to "Create New Post", new_post_path %>
<div>
  <% @posts.each do |post| %>
    <div>
      <h2><%= link_to post.title, post_path(post) %></h2>
      <p>by <%= post.user.email %></p>
      <%# Now that posts are associated with users, you can list the author for every post / comment %>
      <p>Last Update: <%= post.updated_at %></p>
      <p><%= post.content %></p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_area :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= link_to "Back", posts_path %>
<article>
  <h2><%= @post.title %></h2>
  <p>by <%= @post.user.email %></p>
  <p>Last Update: <%= @post.updated_at %></p>
  <p><%= @post.content %></p>
  <% if @post.user == current_user %>
    <%= link_to "Edit Post", edit_post_path(@post) %>
    <%= link_to "Delete Post", post_path(@post), method: :delete %>
  <% end %>
  <%# And now with user associations, you can set up user permissions. Like only
  allowing the owner of the post to edit / delete it (if statement above) %>
  <h4>Comments</h4>
  <%= link_to "Add New Comment", new_post_comment_path(@post) %>
  <% @post.comments.each do |comment| %>
    <div>
      <p><%= comment.user.email %> - <%= comment.updated_at %></p>
      <p><%= comment.content %></p>
      <% if comment.user == current_user %>
        <%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %>
        <%= link_to "Delete Comment", post_path(@post), method: :delete %>
      <% end %>
    </div>
  <% end %>
</article>

app/views/users/_form.html.erb
<%= video_tag "awesome Sony ultra hd food 4K Demo video 2016", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>

app/views/users/show.html.erb
<%= video_tag "awesome Sony ultra hd food 4K Demo video 2016", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>